export const FETCH_POKEMON_INIT = "FETCH_POKEMON_INIT";
export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCHED_POKEMON = "FETCHED_POKEMON";
export const FETCH_POKEMON_FAILED = "FETCHED_POKEMON_FAILED";
